#!/bin/bash

echo "=================================================================="
echo "  COSMIC Desktop - Configuração Manual de Atalhos"
echo "=================================================================="
echo ""
echo "❌ PROBLEMA: O COSMIC usa Wayland e não suporta configuração"
echo "   automática de atalhos via arquivos ou scripts."
echo ""
echo "✅ SOLUÇÃO: Você PRECISA adicionar os atalhos manualmente"
echo "   pela interface gráfica do Settings."
echo ""
echo "=================================================================="
echo ""
echo "🚀 Vou abrir o Settings para você..."
echo ""

# Tenta abrir o Settings do COSMIC
if flatpak-spawn --host cosmic-settings 2>/dev/null; then
    echo "✅ Settings aberto!"
elif flatpak-spawn --host gnome-control-center 2>/dev/null; then
    echo "✅ Control Center aberto!"
else
    echo "⚠️  Não consegui abrir automaticamente. Abra manualmente:"
    echo "   - Procure 'Settings' no launcher"
fi

echo ""
echo "=================================================================="
echo "  INSTRUÇÕES - Adicione estes 6 atalhos:"
echo "=================================================================="
echo ""
echo "Vá em: Settings → Keyboard → View and Customize Shortcuts"
echo "        → Custom Shortcuts (ou clique no botão '+' ou 'Add')"
echo ""
echo "----------------------------------------------------------------"
echo "1️⃣  Nome: Helper Record"
echo "   Atalho: Ctrl+D"
echo "   Comando: curl -X POST http://localhost:3000/toggle-recording"
echo ""
echo "2️⃣  Nome: Helper Focus"
echo "   Atalho: Ctrl+I"
echo "   Comando: curl -X POST http://localhost:3000/bring-to-focus-and-input"
echo ""
echo "3️⃣  Nome: Helper Capture"
echo "   Atalho: Ctrl+Shift+X"
echo "   Comando: curl -X POST http://localhost:3000/capture-screen"
echo ""
echo "4️⃣  Nome: Helper Display 1"
echo "   Atalho: Ctrl+Shift+1"
echo "   Comando: curl -X POST http://localhost:3000/move-to-display/0"
echo ""
echo "5️⃣  Nome: Helper Display 2"
echo "   Atalho: Ctrl+Shift+2"
echo "   Comando: curl -X POST http://localhost:3000/move-to-display/1"
echo ""
echo "6️⃣  Nome: Helper Focus Alt"
echo "   Atalho: Ctrl+Shift+I"
echo "   Comando: curl -X POST http://localhost:3000/bring-to-focus-and-input"
echo ""
echo "=================================================================="
echo ""
echo "💡 DICA: Copie e cole os comandos daqui para não errar!"
echo ""
echo "=================================================================="
